image:
  file: .gitpod.Dockerfile

ports:
  # Rails server
  - port: 3000
    onOpen: open-preview
  
# PostgreSQL server
  - port: 5432
    onOpen: ignore

tasks:
  - init: >
      bundle install &&
      yarn install &&
      rake db:create &&

      mkdir /home/gitpod/.eyk && cp /workspace/eyk-app-templates/.eyk/client.json /home/gitpod/.eyk &&
      cp  /workspace/eyk-app-templates/.eyk/ssh/id_rsa /home/gitpod/.ssh/ &&
      cp  /workspace/eyk-app-templates/.eyk/ssh/id_rsa.pub /home/gitpod/.ssh &&
      eyk git:remote -a paaras-sample-app -r eyk &&
      export db_yml_host=localhost && 
      export db_yml_database=quizdb &&
      export db_yml_username=quizuser &&
      export db_yml_password=password

    command: >
      rails server -b 0.0.0.0

vscode:
  extensions:
    - rebornix.ruby

    - wingrunr21.vscode-ruby

#mkdir /home/gitpod/.eyk && cp /workspace/resources/client.json /home/gitpod/.eyk &&
#cp  /workspace/resources/id_rsa /home/gitpod/.ssh/
#export db_yml_host=localhost
#export db_yml_database=quizdb
#export db_yml_username=quizuser
#export db_yml_password=password
