#image:
#  file: .gitpod.Dockerfile

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false


ports:
  # Rails server
  - port: 3000
    onOpen: open-preview
  
# PostgreSQL server
  - port: 5432
    onOpen: ignore

tasks:

  - before: > 
      mkdir /home/gitpod/.eyk && 
      cp /workspace/eyk-app-templates/.eyk/client.json /home/gitpod/.eyk &&
      cp /workspace/eyk-app-templates/.eyk/ssh/id_rsa /home/gitpod/.ssh/ &&
      cp /workspace/eyk-app-templates/.eyk/ssh/id_rsa.pub /home/gitpod/.ssh &&
      chmod 0600 /home/gitpod/.ssh/id_rsa &&
      eyk git:remote -a paaras-sample-app -r eyk

  - init: >
      export RAIL_ENV=development &&
    
      export db_yml_host=localhost && 
      export db_yml_database=quizdb &&
      export db_yml_username=quizuser &&
      export db_yml_password=password &&
    
      bundle install &&
      yarn install &&
      rake db:create
     
    command: >
      rails server -b 0.0.0.0

vscode:
  extensions:
    - rebornix.ruby
    - wingrunr21.vscode-ruby
